name:  Reporte de Error
description: Reporta un error en el contenido, c贸digo o documentaci贸n
title: '[BUG] '
labels: ['bug', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar un error. Esto nos ayuda a mejorar el bootcamp para todos los estudiantes.

  - type: dropdown
    id: week
    attributes:
      label: Semana Afectada
      description: 驴En qu茅 semana encontraste el error?
      options:
        - Week 01 - Fundamentos
        - Week 02 - SOLID
        - Week 03 - Patrones Arquitect贸nicos
        - Week 04 - Dise帽o de Componentes
        - Week 05 - Patrones de Dise帽o
        - Week 06 - Arquitecturas Modernas
        - Week 07 - Cloud
        - Week 08 - Seguridad
        - Week 09 - Proyecto Final
        - Documentaci贸n General
        - Configuraci贸n/Setup
        - Otro
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Categor铆a
      description: 驴Qu茅 tipo de error encontraste?
      options:
        - C贸digo con errores
        - Explicaci贸n incorrecta
        - Diagrama incorrecto
        - Link roto
        - Typo/Ortograf铆a
        - Error en ejercicio
        - Error en proyecto
        - Otro
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n del Error
      description: Describe claramente qu茅 est谩 mal
      placeholder: |
        Por ejemplo:
        - El c贸digo en el archivo X no funciona porque...
        - La explicaci贸n de Y dice Z pero deber铆a decir...
        - El diagrama muestra A conectado a B, pero en realidad...
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Ubicaci贸n
      description: 驴D贸nde est谩 el error?
      placeholder: |
        Archivo: bootcamp/week-02/1-teoria/solid-principles.md
        L铆nea: 45-50
        Secci贸n: "Principio Open/Closed"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento Esperado
      description: 驴Qu茅 deber铆a pasar o decir en su lugar?
      placeholder: Explica cu谩l ser铆a el contenido o comportamiento correcto
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamiento Actual
      description: 驴Qu茅 pasa o dice actualmente?
      placeholder: Describe lo que realmente sucede o dice
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Pasos para Reproducir (si aplica)
      description: Si es un error de c贸digo, 驴c贸mo reproducirlo?
      placeholder: |
        1. Ir a 'bootcamp/week-02/2-practicas/...'
        2. Ejecutar el archivo '...'
        3. Ver error en consola
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Si es relevante, agrega capturas de pantalla
      placeholder: Arrastra y suelta im谩genes aqu铆
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Entorno (si es relevante)
      description: Informaci贸n de tu entorno si el error es de c贸digo
      placeholder: |
        - OS: [Ubuntu 22.04 / macOS 14 / Windows 11]
        - Node.js: [v20.11.0]
        - pnpm: [v8.15.0]
        - Editor: [VS Code 1.85]
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Contexto Adicional
      description: Cualquier otra informaci贸n que pueda ser 煤til
      placeholder: Informaci贸n adicional, sugerencias, etc.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Por favor verifica lo siguiente
      options:
        - label: He buscado en los issues existentes y este error no ha sido reportado
          required: true
        - label: He proporcionado toda la informaci贸n solicitada
          required: true
        - label: Este error afecta el aprendizaje o la funcionalidad del material
          required: true
